temperature-map: &temperature-map
  dimensions: 2
  type: CONSTANT

stages:
  - type: REPLACE_LIST
    sampler: *temperature-map

    default-from: deep-ocean
    default-to:
      - deep-ocean-tropical: 1

    to:

      ocean:
        - ocean-tropical: 1

      coast-flat:
        - coast-flat-tropical: 1

      coast-hills-small:
        - coast-hills-small-tropical: 1

      coast-hills-large:
        - coast-hills-large-tropical: 1

      coast-mountains-small:
        - coast-mountains-small-tropical: 1

      coast-mountains-large:
        - coast-mountains-large-tropical: 1

      flat:
        # - PALM_BEACH: 1
        - BEACH: 1

      hills-small:
        - PALM_BEACH: 1
        - PALM_FOREST: 1
        # - ROCKY_DESERT: 1
        # - SANDSTONE_WETLANDS: 1

      hills-large:
        - JUNGLE_HILLS: 1

      mountains-small:
        - TEMPERATE_MOUNTAINS: 1
        - ROCKY_BUMPY_MOUNTAINS: 1

      mountains-large:
        # - BAMBOO_JUNGLE_MOUNTAINS: 1
        - JUNGLE_MOUNTAINS: 1
